Борзов Артем
urfu-2016/markup-task-5 pull request #37
Opened 2016-11-07 14:39 UTC by Qoter

- Не все требования

2016-11-07 14:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-08 19:44 UTC, Qoter commented
🍏

2016-11-11 18:02 UTC, bazhenova commented
Привет. Давай добавим побольше котиков)

2016-11-11 18:15 UTC, bazhenova commented
И для начала пройдемся по внешнему виду и требованиям:
1) имя у котика должно быть **ссылкой**
2) эффекты при наведении на имя и на категорию выглядят не очень - у тебя начинают двигаться звезды, цена и описание, от этого начинает рябить в глазах
3) Открыла в браузере вывод списком, почему-то не на всю ширину, фиксированная ширина в данном случае - плохо
![image](https://cloud.githubusercontent.com/assets/12410663/20225348/af3ac1e6-a864-11e6-9bfa-80d85e35029f.png)

2016-11-11 18:17 UTC, bazhenova commented
Когда показываем списком, у некоторых котиков остается пустое место
![image](https://cloud.githubusercontent.com/assets/12410663/20225404/f1d964da-a864-11e6-9155-9de60a995f1b.png)

2016-11-11 18:18 UTC, bazhenova commented
Звезда переехала на новую строку, давай будем всегда держать их на одной строке
![image](https://cloud.githubusercontent.com/assets/12410663/20225434/2abaab56-a865-11e6-8b98-b65ac76d8556.png)

2016-11-11 18:21 UTC, bazhenova commented
И еще у меня такое чувство, что ты поленился сделать это задание хорошо. Можно же было придумать какое-нибудь описание для каждого котика (учитывая, что их у тебя всего 4), а то "Описание для Гоши", "Описание для Маши", ... выглядят не очень

2016-11-11 18:23 UTC, bazhenova commented on index.html
> +            <img class="image" src="images/2.jpg" alt="" title="">
`alt` и `title` должны отвечать на вопрос: "Что изображено на картинке?" Поправь во всем файле

2016-11-11 18:23 UTC, bazhenova commented on index.html
> +        <div class="property-container">
довольно странное название класса, переименуй

2016-11-11 18:34 UTC, bazhenova commented on index.css
> +    height: 300px;
вот из-за этого у тебя остается место после картинки, когда у тебя выбрано отображение списком

2016-11-11 18:34 UTC, bazhenova commented on index.css
> +    width: 800px;
из-за этого нет адаптивности

2016-11-11 18:35 UTC, bazhenova commented
🍅

2016-11-13 19:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-13 19:16 UTC, bazhenova commented
По-моему, будет выглядеть намного лучше, если в отображении списком имя и категорию подвинуть влево
![image](https://cloud.githubusercontent.com/assets/12410663/20248167/8ea2156e-a9ff-11e6-8d98-9475f1338f57.png)

2016-11-13 19:18 UTC, bazhenova commented
А вообще стало выглядеть намного лучше, чем было изначально. Молодец, хорошо постарался)

2016-11-13 19:18 UTC, bazhenova commented
🚀

2016-11-13 19:30 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-14 10:11 UTC, Qoter commented
🍏

2016-11-15 09:25 UTC, mokhov requested changes
🍅

2016-11-15 09:25 UTC, mokhov commented on index.html
> +    <span>Enable listview</span>
Почему это не label к инпуту?

2016-11-15 09:25 UTC, mokhov commented on index.html
> +    <input class="switch-listview" type="checkbox">
input съехал на другую строчку – не красиво

2016-11-15 09:25 UTC, mokhov commented on index.html
> +            <img class="image" src="images/1.jpg" alt="Даша" title="Даша">
Общепринятый паттерн – когда наводишься на ссылку реагирует картинка, а когда на картинку ссылка. Хочется и здесь сделать так же

2016-11-15 09:25 UTC, mokhov commented on index.css
> +.empty-star::after
Мы этому вас научим, но вообще зависимые классы (типа star-empty-star) лучше начинать одинаково, т.е в данном случае должно быть (star – star-empty)

2016-11-15 09:25 UTC, mokhov commented on index.css
> +    box-sizing: border-box;
Зачем здесь border-box, если не заданы ни padding, ни border?

2016-11-15 09:25 UTC, mokhov commented on index.html
> +            <div class="price"><div class="old-price">10000</div>9000 &#8381;</div>
Хорошо – что класс соответствует общей стилистике. Плохо – 1. см. выше про именование зависимых классов. 2. Т.к здесь div то приходится переопределять тип отображения, а можно было использовать другой тег и не делать этого. 3. У inline элементов нужно не забывать про пробелы, а не задавать отступы margin'ами

2016-11-15 09:25 UTC, mokhov commented on index.html
> +            Американская короткошерстная  - Зачем кошке много шерсти ? Лучше когда коротко и четко!.
Здесь восклицательный знак в воздухе повис

2016-11-15 09:25 UTC, mokhov commented on index.html
> +            Американская короткошерстная  - Зачем кошке много шерсти ? Лучше когда коротко и четко!.
И что за `!.`?

2016-11-15 09:25 UTC, mokhov commented on index.html
> +            <div class="category">Грустишка</div>
Категория может быть только одна?

2016-11-15 17:29 UTC, qoter commented on index.html
> +            <div class="category">Грустишка</div>
@mokhov а разве оговаривалось иное?

2016-12-12 20:15 UTC, closed without merging