Старков Дима
urfu-2016/markup-task-5 pull request #6
Opened 2016-11-03 22:23 UTC by dimastark

Фух

2016-11-03 22:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-05 12:08 UTC, bazhenova commented
Сначала пройдемся по верстке.
![image](https://cloud.githubusercontent.com/assets/12410663/20029881/5eb9ad20-a37a-11e6-9fc0-a1744562cf5f.png)
Давай сделаем их одной высоты

2016-11-05 12:14 UTC, bazhenova commented
Есть несколько котиков разной цены (?) Может быть они будут в одних единицах измерения?
![image](https://cloud.githubusercontent.com/assets/12410663/20029897/2964cc58-a37b-11e6-94c0-c36584b3d3f3.png) ![image](https://cloud.githubusercontent.com/assets/12410663/20029899/330c3d40-a37b-11e6-9709-bc4e8e94ed12.png) ![image](https://cloud.githubusercontent.com/assets/12410663/20029900/4002a34a-a37b-11e6-90f5-36665b84e120.png)

2016-11-05 12:17 UTC, bazhenova commented
![image](https://cloud.githubusercontent.com/assets/12410663/20029910/7e487a80-a37b-11e6-9c28-71337d9ab93c.png)
Если ты решил использовать `border`, то давай будем делать это красиво) Если ничего не придумаешь, то напиши мне в slack, может чего подскажу. Но сначала подумай сам 😉

2016-11-05 12:20 UTC, bazhenova commented
И еще замечания по поводу звездочек. Давай поменяем цвета: при наведение сделать цвет бледным, а при фиксировании рейтинга - обычный желтый.

2016-11-05 12:23 UTC, bazhenova commented
![image](https://cloud.githubusercontent.com/assets/12410663/20029948/8c7f1df6-a37c-11e6-886b-5763ffbdce0b.png)
Тут тоже некрасиво столько места оставлять

2016-11-05 12:26 UTC, bazhenova commented
+ мое пожелание: задай какие-нибудь дефолтные значения для звездочек, а то получается, что ни один котик не оценен :scream_cat:

2016-11-05 12:30 UTC, bazhenova commented
Есть нериализованное требование: 
```
Обрезать длинные имена котиков (=^ ◡ ^=)
``` 
Придумай какое-нибудь длинное имя или увеличь шрифт, чтобы это требование можно было реализовать

2016-11-05 12:32 UTC, bazhenova commented
🍅

2016-11-07 13:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 17:34 UTC, dimastark commented
Пока так

2016-11-09 06:47 UTC, bazhenova commented
![image](https://cloud.githubusercontent.com/assets/12410663/20129535/445df684-a672-11e6-811e-9dd3bd57106c.png)
Котик без имени:scream_cat:

2016-11-09 06:49 UTC, bazhenova commented
Есть такое место между звездочками, на которое наводишь и подсвечивается вся следующая звездочка

2016-11-09 06:51 UTC, bazhenova commented
![image](https://cloud.githubusercontent.com/assets/12410663/20129610/c8a25764-a672-11e6-8001-e74c10541f7f.png)
Тут все еще есть некрасивые пустые места

2016-11-09 06:52 UTC, bazhenova commented on index.css
> +/* For stars (COPY-PASTE FROM GOOGLE) */
😑 😑 😑

2016-11-09 06:53 UTC, bazhenova commented on index.css
> +/* Ctrl+C / Ctrl+V end */
😑 😑 😑

2016-11-09 06:55 UTC, bazhenova commented on index.html
> +            <div class="cat-description">FUS-RO-MYAH!</div>
😄

2016-11-09 06:57 UTC, bazhenova commented
Есть еще пара замечаний по верстке + я надеюсь, что ты разобрался в копипасте)  а так передаю ментору

2016-11-09 06:57 UTC, bazhenova commented
🚀

2016-11-09 11:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-10 06:41 UTC, VorontsovMaxim requested changes
🍅 
Есть замечания. Советую все таки разобраться в копипасте

2016-11-10 06:41 UTC, VorontsovMaxim commented on index.css
> +.rating:not(:checked) > .star-label:hover ~ .star-label
А ты разбирался в этом копипасте?
`.rating` это в твоем случае `<p>`, может ли он быть `:checked`?
Еще ни к чему писать избыточные селекторы. Вряд ли на твоей странице будут `.rating-input` вне `.rating`

2016-11-10 06:41 UTC, VorontsovMaxim commented on index.css
> +.rating > .rating-input:checked ~ .star-label:hover,
Про избыточность аналогично

2016-11-10 06:41 UTC, VorontsovMaxim commented on index.css
> +.rating > .rating-input:checked ~ .star-label:hover,
Этот селектор включает в себя предыдущий

2016-11-10 06:41 UTC, VorontsovMaxim commented on index.html
> +    <div class="content">
Не стоит забывать про семантическую разметку. При необходимости можно освежить в памяти первую лекцию

2016-11-10 06:41 UTC, VorontsovMaxim commented on index.html
> +                <p class="cat-cost">100£</p>
Тег `<p>` используется для текстовых абзацев. Для категории, рейтинга и стоимости он не очень подходит

2016-11-10 06:41 UTC, VorontsovMaxim commented on index.html
> +                <img class="cat-img" src="images/cat_00.png" alt="Нулевой котик" title="Нулевой">
`alt` и `title` должны отвечать на вопрос "Что изображено на картинке?"
Сейчас от порядкового номера особого толку нет

2016-11-10 06:42 UTC, VorontsovMaxim commented
Еще обрезаются картинки 
![2016-11-10 11-21-38](https://cloud.githubusercontent.com/assets/14827792/20167066/c243cf9c-a73a-11e6-91da-c3dcbe536dbf.png)

2016-11-10 08:15 UTC, dimastark commented on index.css
> +.rating:not(:checked) > .star-label:hover ~ .star-label
Ладно) Видимо все таки придется разобраться

2016-11-10 08:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-11 06:12 UTC, VorontsovMaxim commented
🍅 
Сейчас уже все хорошо, но картинки все еще обрезаются
Давай это исправим и на этом все

2016-11-11 17:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-11 17:46 UTC, dimastark commented
Нашел неправильное правило, теперь вроде не обрезаются

2016-11-12 07:07 UTC, VorontsovMaxim commented
Принято. В следующий раз пожалуйста делай все новые правки отдельными коммитами, чтобы мне было удобнее смотреть, что именно ты исправил

2016-11-12 07:07 UTC, closed without merging